name: First Work Flow
on: workflow_dispatch
jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo Hello, world!

      - name: Print goodbye
        run: | 
            echo "Done - Bye"
            echo "Bye 2"
